services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis_linux_dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
    tty: true
    stdin_open: true
