include_guard(GLOBAL)

function(redis_enable_sanitizers target enable_asan enable_ubsan)
  if(MSVC)
    if(enable_asan)
      target_compile_options(${target} PRIVATE /fsanitize=address)
      target_link_options(${target} PRIVATE /fsanitize=address)
    endif()
    return()
  endif()

  set(SANITIZER_FLAGS "")
  if(enable_asan)
    list(APPEND SANITIZER_FLAGS -fsanitize=address)
  endif()
  if(enable_ubsan)
    list(APPEND SANITIZER_FLAGS -fsanitize=undefined)
  endif()

  if(SANITIZER_FLAGS)
    target_compile_options(${target} PRIVATE ${SANITIZER_FLAGS} -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE ${SANITIZER_FLAGS})
  endif()
endfunction()
